### ISSUE TITLE
Update an icon sdk for python to support the json rpc 3.0. 

### ISSUE THREAD

**Issue by boyeonchoi** [icon-project/icon_sdk_for_python#11]
Update an icon sdk for python to support the json rpc 3.0 specification like json schema, parameters, new methods.

**Comment by boyeonchoi** [comment]
Require a spec document like README.md about the icon sdk for python supporting the json rpc 3.0.

**Comment by boyeon555** [comment]
This document is for SDK based on ICON JSON RPC API V2. We do not update this project any longer! Please refer to the latest version SDK based on ICON JSON RPC API V3 (https://github.com/icon-project/icon-sdk-python) instead.
