### ISSUE TITLE
Are there going to be other languages than Python?

### ISSUE THREAD

**Issue by klosor** [icon-project/icon_sdk_for_python#16]
Java? C/C++? C#?

**Comment by tomnuen** [comment]
After Java, a port to C# would be awesome.

**Comment by Spl3en** [comment]
If the community manages to make a C# port based on the Python SDK implementation, I wonder if the pull request would be accepted ?

**Comment by boyeon555** [comment]
I am sorry that we don't have any plan to support C# yet. But you can fork the project and participate in the project for SDK. And you can make your own SDK by referring to this document for the design.
