### ISSUE TITLE
Can we change import rule? 

### ISSUE THREAD

**Issue by JinhoYoo-icon-project** [icon-project/icon_sdk_for_python#2]
Currently we import iconsdk like following. 

```from icx.wallet.wallet import Wallet```

Then it seems redundant that use ``` wallet.wallet```.  I recommend ```from icx.wallet import Wallet```.

**Comment by boyeonchoi** [comment]
Thanks for giving the opinion. Import rule is changed that it is from 'from icx.wallet.wallet import Wallet' to 'from icx.wallet import Wallet'

**Comment by JinhoYoo-icon-project** [comment]
Closed in https://github.com/icon-project/icon_sdk_for_python/pull/5
