### ISSUE TITLE
Use wheel to generate package

### ISSUE THREAD

**Issue by JinhoYoo-icon-project** [icon-project/icon_sdk_for_python#9]
To provide a package with C extension, we need to use [wheel](https://wheel.readthedocs.io/en/stable/index.html) without C library compilation.

**Comment by boyeon555** [comment]
This document is for SDK based on ICON JSON RPC API V2. We do not update this project any longer! Please refer to the latest version SDK based on ICON JSON RPC API V3 (https://github.com/icon-project/icon-sdk-python) instead.
